# Generated by Django 3.2.5 on 2021-07-14 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_calories', models.IntegerField(verbose_name='Total Calories')),
                ('protein_grams', models.IntegerField(verbose_name='Protein(g)')),
                ('carbohydrate_grams', models.IntegerField(verbose_name='Carbohydrate(g)')),
                ('fat_grams', models.IntegerField(verbose_name='Fats(g)')),
            ],
        ),
    ]
