# Generated by Django 3.2.5 on 2021-07-14 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_name', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredients',
            new_name='Ingredient',
        ),
    ]
