# Generated by Django 3.2.5 on 2021-07-15 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_name', '0002_rename_ingredients_ingredient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
