# Generated by Django 3.2.5 on 2021-07-15 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website_name', '0003_delete_ingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=200)),
                ('total_calories', models.IntegerField(verbose_name='Total Calories')),
                ('protein_grams', models.IntegerField(verbose_name='Protein(g)')),
                ('carbohydrate_grams', models.IntegerField(verbose_name='Carbohydrate(g)')),
                ('fat_grams', models.IntegerField(verbose_name='Fats(g)')),
            ],
        ),
    ]
