# Generated by Django 3.2.5 on 2021-07-22 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_name', '0005_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_id', models.IntegerField(verbose_name='FoodID')),
                ('food_code', models.IntegerField(verbose_name='FoodCode')),
                ('food_group_id', models.IntegerField(verbose_name='Food GroupID')),
                ('food_source_id', models.IntegerField(verbose_name='Food SourceID')),
                ('food_desc', models.CharField(max_length=200)),
                ('food_date_of_entry', models.DateField(verbose_name='Food Date of Entry')),
            ],
        ),
        migrations.CreateModel(
            name='NutrientAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_id', models.IntegerField(verbose_name='FoodID')),
                ('nutrient_id', models.IntegerField(verbose_name='NutrientID')),
                ('nutrient_value', models.FloatField(verbose_name='Nutrient Value')),
                ('nutrient_source_id', models.IntegerField(verbose_name='Nutrient SourceID')),
                ('nutrient_date_of_entry', models.DateField(verbose_name='Nutrient Date of Entry')),
            ],
        ),
        migrations.CreateModel(
            name='NutrientName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nutrient_id', models.IntegerField(verbose_name='NutrientID')),
                ('nutrient_code', models.IntegerField(verbose_name='Nutrient Code')),
                ('nutrient_symbol', models.CharField(max_length=200)),
                ('nutrient_unit', models.CharField(max_length=200)),
                ('nutrient_name', models.CharField(max_length=200)),
                ('nutrient_decimals', models.IntegerField(verbose_name='Nutrient Decimals')),
            ],
        ),
    ]
