# Generated by Django 3.2.5 on 2021-07-22 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_name', '0006_foodname_nutrientamount_nutrientname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodName',
        ),
        migrations.RemoveField(
            model_name='nutrientamount',
            name='id',
        ),
        migrations.RemoveField(
            model_name='nutrientname',
            name='id',
        ),
        migrations.AlterField(
            model_name='nutrientamount',
            name='food_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nutrientname',
            name='nutrient_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
