# Generated by Django 3.2.5 on 2021-07-22 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_name', '0007_auto_20210721_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodName',
            fields=[
                ('food_id', models.IntegerField(primary_key=True, serialize=False)),
                ('food_code', models.IntegerField()),
                ('food_group_id', models.IntegerField()),
                ('food_source_id', models.IntegerField()),
                ('food_desc', models.CharField(max_length=200)),
                ('food_desc_f', models.CharField(max_length=200)),
                ('food_date_of_entry', models.DateField()),
                ('food_date_of_publication', models.DateField(default=None)),
                ('country_code', models.IntegerField(default=None)),
                ('scientific_name', models.CharField(default=None, max_length=200)),
            ],
        ),
    ]
