# Generated by Django 3.2.5 on 2021-07-23 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_name', '0008_foodname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NutrientAmount',
        ),
        migrations.AlterField(
            model_name='foodname',
            name='food_date_of_entry',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='foodname',
            name='food_date_of_publication',
            field=models.CharField(max_length=200),
        ),
    ]
