# Generated by Django 3.2.5 on 2021-07-23 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_name', '0010_nutrientamount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NutrientAmount',
        ),
    ]
