# Generated by Django 3.2.5 on 2021-07-23 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_name', '0013_delete_nutrientamount'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutrientAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_id', models.IntegerField()),
                ('nutrient_id', models.IntegerField()),
                ('nutrient_value', models.FloatField()),
                ('nutrient_source_id', models.IntegerField()),
                ('nutrient_date_of_entry', models.CharField(max_length=200)),
            ],
        ),
    ]
