# Generated by Django 3.2.5 on 2021-08-18 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_name', '0015_auto_20210724_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serving_size', models.IntegerField()),
                ('serving_unit', models.CharField(max_length=200)),
                ('calories', models.IntegerField()),
                ('total_fat', models.IntegerField(default=0)),
                ('saturated_Fat', models.IntegerField(default=0)),
                ('unsaturated_Fat', models.IntegerField(default=0)),
                ('trans_fat', models.IntegerField(default=0)),
                ('cholesterol', models.IntegerField(default=0)),
                ('total_carbs', models.IntegerField(default=0)),
                ('dietary_fiber', models.IntegerField(default=0)),
                ('total_sugar', models.IntegerField(default=0)),
                ('added_sugar', models.IntegerField(default=0)),
                ('protein', models.IntegerField(default=0)),
            ],
        ),
    ]
