# Generated by Django 3.2.5 on 2021-07-31 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_group_id', models.IntegerField()),
                ('food_group_code', models.IntegerField()),
                ('food_group_name', models.CharField(max_length=200)),
                ('food_group_name_french', models.CharField(max_length=200)),
            ],
        ),
    ]
