# Generated by Django 3.2.5 on 2021-08-04 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0002_foodgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodgroup',
            name='id',
        ),
        migrations.AlterField(
            model_name='foodgroup',
            name='food_group_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nutrientamount',
            name='food_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_loader.foodname'),
        ),
    ]
