# Generated by Django 3.2.5 on 2021-08-18 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0003_auto_20210803_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_id', models.IntegerField()),
                ('measure_id', models.IntegerField()),
                ('conversion_factor_value', models.FloatField()),
                ('conversion_factor_date_of_entry', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MeasureName',
            fields=[
                ('measure_id', models.IntegerField(primary_key=True, serialize=False)),
                ('measure_description', models.CharField(max_length=200)),
            ],
        ),
    ]
